# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2293e4bb5cfc9d6c4b29f3390d93f9a0519f08ee8875ebba9cccfeb90bd54a8a909c42abaa8b3fe324d3f5d533b8dd41bcc496904cc7ec8ebafa2dc07d2607e

test:
  secret_key_base: 5977fe2f4e5f94168830562f7782354e19146e60a8d5705d9e141e488c278876c0c827dba6d524668aaf89b6c600eedd536917481b3434a148559d998f16b074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
